### ISSUE TITLE
FSharp.Core, Version=7.0.0.0

### ISSUE THREAD

**Issue by rastreus** [CaptnCodr/Fli#47]
I currently have a deployment with the following .NET SDKs available:
```bash
dotnet --list-sdks
3.1.404
5.0.403
6.0.400
```
When running a Fli test with version 1.0.0 and 0.11.0, I get the following error:
```bash
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Can the FSharp.Core version be set to greater than or equal to 6 in the `paket.dependencies` file so .NET 6 can be used?**

```
nuget FSharp.Core >= 6
```

Thanks

**Comment by CaptnCodr** [comment]
Hey @rastreus, 
thank you for opening an issue to that.
This has been fixed in v1.0.1. It's already available at nuget.
