### ISSUE TITLE
Apps are not displayed when run as admin

### ISSUE THREAD

**Issue by mrboring** [CaptnCodr/Fli#64]
Hi

I'm trying to launch Image for Windows. This is a Windows application. It launches and I can see it in Task Manager, but the window is not visible.

I'm running VS Code elevated as the application requires admin rights.

I'm using the following code inside an fsx file:

```f#
#r "nuget: Fli, 1.101.0"

open System
open System.IO
open Fli

cli {
        Exec @"C:\Program Files (x86)\TeraByte Drive Image Backup and Restore Suite\imagew64.exe"
        WorkingDirectory @"C:\Program Files (x86)\TeraByte Drive Image Backup and Restore Suite"
}
|> Command.execute
```

I tried the above with and without the `WorkingDirectory` line. I also tried running the fsx file from the command line:

```
dotnet fsi '.\Image For Windows Runner.fsx'
```

If I run the follwing from an elevated PowerShell prompt, it works fine:

```powershell
& "C:\Program Files (x86)\TeraByte Drive Image Backup and Restore Suite\imagew64.exe"
```

I also tried Disk2Vhd which also requires elevation. Same results, I can see it in task manager, but the window is not visible. Running it from PowerShell works:

```powershell
& "C:\Users\<removed>\AppData\Local\Microsoft\WindowsApps\disk2vhd.exe"

**Comment by CaptnCodr** [comment]
Hi @mrboring, 
can you try with `Verb "open"` to fix this?

**Comment by mrboring** [comment]
I've just tried:

```f#
cli {
        Exec @"C:\Users\Alan\AppData\Local\Microsoft\WindowsApps\disk2vhd.exe"
        Verb "open"
}
|> Command.execute
```

This still ran in the background with no window. Even after I interrupted the script (Ctrl+c):

```powershell
> Get-Process *disk2vhd*

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
     11   133.81     142.26       1.09   13180   1 disk2vhd
```

**Comment by CaptnCodr** [comment]
Ok, try with `Verb "runas"`. 
If this isn't working then I need to dive deeper.

**Comment by CaptnCodr** [comment]
Ok, try with `Verb "runas"`. 
If this isn't working then I need to dive deeper.

**Comment by CaptnCodr** [comment]
Ok, try with `Verb "runas"`. 
If this isn't working then I need to dive deeper.

**Comment by mrboring** [comment]
Still no windows with `runas`:

```f#
cli {
        Exec @"C:\Users\Alan\AppData\Local\Microsoft\WindowsApps\disk2vhd.exe"
        Verb "runas"
}
|> Command.execute
```

I also tried with a built-in app and got the same results:

```f#
cli {
        Exec @"C:\Windows\regedit.exe"
        Verb "runas"
}
|> Command.execute
```

Even without `runas`,  if the app requires elevation (and you're not running the host elevated), UAC is triggered. It looks like this issue is only related to apps requiring elevation.

Running an app that does not require elevation works fine:

```f#

cli {
        Exec @"C:\Windows\notepad.exe"
}
|> Command.execute
```

**Comment by CaptnCodr** [comment]
Thank you for providing information about it. 
I will look for a solution.

**Comment by CaptnCodr** [comment]
Hey @mrboring, 
I have a explanation for this issue:
When you start a process over `Exec`, the `WindowStyle` is in `Fli` on `WindowStyle.Hidden`, because cli programs are usually run as "hidden" programm/process in the background. (This is intended.)

But I have a solution for you to bypass it, just run it in a shell context, i.e.:
```fsharp
cli {
    Shell PWSH
    Command @"C:\Windows\regedit.exe"
}
|> Command.execute
```
Here, the `pwsh.exe` process will be started with `WindowStyle.Hidden`, but the command in that `pwsh.exe` will be executed with `WindowStyle.Normal` which will open the programs window.

I hope this is a passable solution for you. 🙂

**Comment by CaptnCodr** [comment]
If you need to pass in the `-NoProfile` then I would suggest doing it with the `Exec` context and arguments:
```fsharp
cli {
    Exec "pwsh.exe"
    Arguments [| "-NoProfile"; "-Command"; @"C:\Windows\regedit.exe" |]
}
|> Command.execute
```

I'll think about that `WindowStyle` feature. 😄
