### ISSUE TITLE
Implement Zero value for computation expression.

### ISSUE THREAD

**Issue by AlexStory** [CaptnCodr/Fli#69]
Would it be possible to implement the `Zero` value for the cli computation expression? This is needed for letting other values be added conditionally.

In my current process, I'm trying to add the output logging if the user specifies  a log file. and it would allow the following to happen

```fs
cli {
    Command "command"
    Arguments ["arg1"; "arg2"]
    
    if logPath.isSome then
        Output logPath.Value
}
```

**Comment by CaptnCodr** [comment]
Thank you, that looks doable. 😊

**Comment by CaptnCodr** [comment]
Hey @AlexStory,
I was playing around with the `Zero` function in CEs.
Unfortunately, it's not possible to implement it in `Fli`.

I can offer you another thing where I need to fix something anyways:
a condition beforehand or inline:
`let output = if logPath.isSome then logPath.Value else ""`
or 
`let output = if logPath.isSome then Output.File(logPath.Value) else Output.None`

```
cli {
    Command "command"
    Arguments ["arg1"; "arg2";]
    Output output // or inline condition
```

What do you think?

**Comment by AlexStory** [comment]
For my personal case that would work, if `Output ""` is treated the same as just not having an Output

**Comment by CaptnCodr** [comment]
This change has been pushed to Nuget in version v1.111.10.
Thank you for your patience. 🙂
